# Generated by Django 4.0.1 on 2022-01-29 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0002_cartoon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cartoon',
        ),
    ]
